export const trendingSlides = [
  {
    title: 'TITLE 1',
    img: '/images/featured/1.jpg',
    netflix: true,
    top10: true,
    newSeason: true,
    newEpisode: false,
    tvRating: 'TV-MA',
    genre: ['dark', 'cerebral', 'psychological'],
    hd: true,
    duration: '2 Seasons',
    match: 98,
  },
  {
    title: 'TITLE 2',
    img: '/images/featured/2.jpg',
    netflix: false,
    top10: true,
    newSeason: false,
    newEpisode: false,
    tvRating: 'R',
    genre: ['explosive', 'action', 'thriller'],
    hd: false,
    duration: '1h 58m',
    match: 78,
  },
  {
    title: 'TITLE 3',
    img: '/images/featured/3.jpg',
    netflix: true,
    top10: false,
    newSeason: false,
    newEpisode: true,
    tvRating: 'TV-14',
    genre: ['reality TV', 'exciting'],
    hd: true,
    duration: '8 Episodes',
    match: 92,
  },
];

export const myListSlides = [
  {
    title: 'TITLE 4',
    img: '/images/featured/7.jpg',
    netflix: false,
    top10: false,
    newSeason: true,
    newEpisode: false,
    tvRating: 'TV-MA',
    genre: ['dark', 'cerebral', 'psychological'],
    hd: true,
    duration: '2 Seasons',
    match: 98,
  },
  {
    title: 'TITLE 5',
    img: '/images/featured/8.jpg',
    netflix: true,
    top10: true,
    newSeason: false,
    newEpisode: true,
    tvRating: 'TV-MA',
    genre: ['dark', 'cerebral', 'psychological'],
    hd: true,
    duration: '2 Seasons',
    match: 98,
  },
  {
    title: 'TITLE 6',
    img: '/images/featured/9.jpg',
    netflix: false,
    top10: false,
    newSeason: false,
    newEpisode: false,
    tvRating: 'TV-MA',
    genre: ['dark', 'cerebral', 'psychological'],
    hd: true,
    duration: '2 Seasons',
    match: 98,
  },
];

export const newSlides = [
  {
    title: 'TITLE 7',
    img: '/images/featured/4.jpg',
    netflix: false,
    top10: true,
    newSeason: true,
    newEpisode: false,
    tvRating: 'TV-MA',
    genre: ['dark', 'cerebral', 'psychological'],
    hd: true,
    duration: '2 Seasons',
    match: 98,
  },
  {
    title: 'TITLE 8',
    img: '/images/featured/5.jpg',
    netflix: true,
    top10: true,
    newSeason: false,
    newEpisode: true,
    tvRating: 'TV-MA',
    genre: ['dark', 'cerebral', 'psychological'],
    hd: true,
    duration: '2 Seasons',
    match: 98,
  },
  {
    title: 'TITLE 9',
    img: '/images/featured/6.jpg',
    netflix: true,
    top10: true,
    newSeason: false,
    newEpisode: false,
    tvRating: 'TV-MA',
    genre: ['dark', 'cerebral', 'psychological'],
    hd: true,
    duration: '2 Seasons',
    match: 98,
  },
];
